// This file is generated by kconfig_compiler from Rocs.kcfg.
// All changes you do to this file will be lost.
#ifndef SETTINGS_H
#define SETTINGS_H

#include <kconfigskeleton.h>
#include <kdebug.h>

class Settings : public KConfigSkeleton
{
  public:

    static Settings *self();
    ~Settings();

    /**
      Set Show text beside icon
    */
    static
    void setShowButtonText( bool v )
    {
      if (!self()->isImmutable( QString::fromLatin1 ( "showButtonText" ) ))
        self()->mShowButtonText = v;
    }

    /**
      Get Show text beside icon
    */
    static
    bool showButtonText()
    {
      return self()->mShowButtonText;
    }

  protected:
    Settings();
    friend class SettingsHelper;


    // ItemPalette
    bool mShowButtonText;

  private:
};

#endif

